# Generated by Django 3.1.4 on 2022-01-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A_colors',
            new_name='A_color',
        ),
        migrations.RenameModel(
            old_name='A_images',
            new_name='A_image',
        ),
        migrations.RenameModel(
            old_name='A_sizes',
            new_name='A_size',
        ),
    ]
